#!/usr/bin/env bash
# Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

f="/etc/passwd"

while IFS= read -r l; do
  user=$(echo "$l" | cut -d ':' -f1)
  GROUP_ID=$(echo "$l" | cut -d ':' -f4)
  HOME_DIRECTORY=$(echo "$l" | cut -d ':' -f6)
  shell=$(echo "$l" | cut -d ':' -f7)
  USER_ID=$(echo "$l" | cut -d ':' -f3)
  pass=$(echo "$l" | cut -d ':' -f2)
  info=$(echo "$l" | cut -d ':' -f5)

  echo "The user $user is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $shell. $USER_ID's place is protected by the passcode $pass, more info about the user here: $info"
done < "$f"
