#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

x=1

while [ "$x" -lt 11 ]; do
  echo "Best School"
  
  if [ "$x" -eq 9 ]; then
    echo "Hi"
  fi

  ((x++))
done
